---
#
# Ansible managed
#
repository:
  description: Install powertop on your system and optimize at boot.
  homepage: https://robertdebock.nl/
  topics: powertop, ansible, molecule, tox, playbook, hacktoberfest
