---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="amazonlinux"
    - image="alpine"
    - image="alpine" tag="edge"
    - image="debian" tag="unstable"
    - image="debian"
    - image="fedora"
    - image="fedora" tag="rawhide"
    - image="opensuse"
    - image="ubuntu"

matrix:
  allow_failures:
    - env: image="alpine" tag="edge"
    - env: image="debian" tag="unstable"
    - env: image="fedora" tag="rawhide"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "JpHzDqYLD4NrCjtLwVgyWwteYO4NGHJ+tsgG+TwE2T3lWXwSyK5FMNu/Y6hHDlL0ZrnU+2peDJt5QvnvY8cO3IMlFPu3diVGHHVrIITVeM4WYeZc8iFXH4SLOzwRQSQHNcUqY3Vs1yr71dEbIJYXCb90/XQQeDRzjWJpltqYpPaoQVi4ATDPJ8UuOXQkKQjFofCEY8AZsL18qJg6MtpX8NH8/cyfGS8muWVLjGIGsVXRsCKkvkjFHITccsVtpI4ko5PNDbQcZwSC7TB+cblLwOGLK8V/eKvzibWPhYmtsm9YWfIscyxOJs+ZjHxOfZbPlSI8fmW72SMK/xeg81EZ9X0sN+kyj3yULhfjQ2QIx10h3rSTZ3mdlh3vJWWcnav1bfxEctWejnPZHBAwb9TKwq35Vhaz45/9EfjZaUAMHORuODUtz291ZoP8mxWdOJ+oVmyO4lq+IUZQp1KV4rhT0MA+MIQM9mlKcVYI4qpZ+FrCjaHpxHyyilx5TCPYYZ8y4CUyo9VmLYu612Zm8KpR8R+WSbei11UVqwWEDukriZSsVDBTeDyz6d6bxfzUnDXD037zJd9d5xlfqTy/xQanLD+DiOanBJAnwCk0f/K+YRDTcpOK2KO/duuLjw/2zoh1nLA+NF/57nClGR2iVPmJN3ry5YOAWb+p1RYib/jQrt0="
  email: false
